[package]
name = "super_clipboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
cli-clipboard = "0.4.0"
eframe = "0.21.3"
egui = "0.21.0"
sysinfo = "0.28.4"
